### ISSUE TITLE
Tracker: FlatGFA Python bindings

### ISSUE THREAD

**Issue by sampsyo** [cucapra/pollen#179]
Here's just a snapshot of some next steps for the Python bindings.

Project infrastructure:

* [ ] CI. #178 added some tests; they should run in GitHub actions. [Maturin](https://www.maturin.rs) has a `generate-ci` command that should help with this.
* [ ] Build docs. Just like we have [auto-published Sphinx docs for mygfa](https://cucapra.github.io/pollen/mygfa/), let's do the same for the FlatGFA module.
* [ ] Publish on PyPI. I believe Maturin/Actions can help with this too.

API "surface area":

* [ ] Mutation. Let's make it possible to build up a graph from scratch.
* [ ] Expose the ops. Things that are currently CLI subcommands (in `cmds.rs`) should be put into a library of useful "ops" on the GFA data structure. This way, you can string together multiple operations in a Python invocation. In the limit, maybe we can reproduce odgi pipelines from our collaborators as Python scripts.

Python niceties:

* [ ] The various objects should probably be made equatable/hashable.
* [ ] Use `str(obj)` on paths, links, steps, etc. to produce GFA string fragments.
* [ ] Names (of paths) should probably by `str` and not `bytes`? Seems fine to assume these are UTF-8. Nucleotide sequences can stay bytes.

**Comment by sampsyo** [comment]
It's on PyPI (and therefore `pip install`able) now: https://pypi.org/project/flatgfa/
